### PR TITLE
fix overflow in SearchHistory

### LINKED ISSUE #277: [BUG] 历史搜索页面overflow
当历史搜索数量超出一屏时，
https://github.com/DanXi-Dev/DanXi/blob/97c48f6f90a74be6b22559a7d631d66894a6b959/lib/page/opentreehole/hole_search.dart#L133
报overflow，同时内部的ListView不能滚动

### PR DESCRIPTION
**Pull request by kooWZ**
The column of search history widget is nested in the main column, leaving the size of search history column uncertain.
This causes overflow when wrapping `ListView` in `Flexible`, or exception when wrapping it in `Expanded`.

After enclosing `Column` in `Expanded`, both `Flexible` and `Expanded` works well with `ListView`.
Closes #277

### CODE REVIEW

File: lib/page/opentreehole/hole_search.dart [hunk 1]
```diff
@@ -58,7 +58,10 @@ class _OTSearchPageState extends State<OTSearchPage> {
   /// The text user inputs.
   final TextEditingController _searchFieldController = TextEditingController();
 
-  Widget _buildSearchHistory(BuildContext context) => Column(
+  /// Use Expanded to avoid the uncertainty of column size,
+  /// thus solving Flexible overflow
+  Widget _buildSearchHistory(BuildContext context) => Expanded(
```
Comment (w568w) [inline lib/page/opentreehole/hole_search.dart:63]: It is not recommended to return a `Expanded` Widget, since it is only valid inside a `Flex` Widget (e.g. `Column`, `Row`, `Flex`). Without proper comments, it might result in coupled modifications when the parent layout is changed later on.

You should, instead, put the wrapping widget in where the parent `Flex` is declared, e.g.

```dart
Column(
  children: [
    // ...
    Expanded(child: _buildSearchHistory(context)),
    // ...
  ]
)
```

**Review by w568w — CHANGES_REQUESTED** [review]

File: lib/page/opentreehole/hole_search.dart (hunk 1 above)
Comment (kooWZ) [reply lib/page/opentreehole/hole_search.dart]: Got it
Moved `Expanded`  inside main `Column`

**Review by w568w — APPROVED** [review]
Tested. LGTM.
