### PR TITLE
many fixes

### LINKED ISSUE #284: [BUG] 图书馆人数和内网检测功能报错
由于复旦系统升级，原图书馆预约网址 10.55.101.62 现在重定向到 libsrs.fudan.edu.cn
用于查询在馆人数的链接 10.55.101.62/api/show 现在提示500错误，导致
1. 图书馆人数功能不能正常使用
2. 依赖于检查这个链接来确定校园网状态的`checkConnection`函数始终返回`false`，在校园网环境下依然提示未连接到内网

如果后续开发基于 10.64.130.6 的空闲教室查询，可以考虑用这个链接作为内网判据

### PR DESCRIPTION
**Pull request by kooWZ**
Closes #284

### CODE REVIEW

**Comment by w568w** [comment]
Seems a large PR! 👍 I will review it as soon as I have some time.

File: lib/page/dashboard/empty_classroom_detail.dart [hunk 1]
```diff
@@ -101,6 +101,32 @@ class EmptyClassroomDetailPageState extends State<EmptyClassroomDetailPage> {
...
+            context: context,
+            builder: (BuildContext context) => PlatformAlertDialog(
+                  title: Text(S.of(context).lan_connection_issue_1),
+                  content: Text(S.of(context).empty_classroom_warning),
+                  actions: <Widget>[
+                    PlatformDialogAction(
+                        child: PlatformText(S.of(context).i_see),
+                        onPressed: () => Navigator.pop(context)),
+                  ],
+                ));
```
Comment (w568w) [inline lib/page/dashboard/empty_classroom_detail.dart:124]: This dialog may pop up **every time** you select a school building or refresh the page.

For a less-intrusive notice, check out:

https://github.com/DanXi-Dev/DanXi/blob/a601dba7f268b0b84bf005ddc9df7c07d2d7d4d0/lib/page/dashboard/exam_detail.dart#L281-L291

This function builds a red-colored card at the top of page, to notify the user that the information could be inaccurate.

File: lib/repository/fdu/empty_classroom_repository.dart [hunk 2]
```diff
@@ -32,17 +113,17 @@ class EmptyClassroomRepository extends BaseRepositoryWithDio {
...
 
-  factory EmptyClassroomRepository.getInstance() => _instance;
+  factory EhallEmptyClassroomRepository.getInstance() => _instance;
 
   /// Get [RoomInfo]s at [buildingName] on [date].
   ///
   /// Request [PersonInfo] for logging in, if necessary.
   Future<List<RoomInfo>?> getBuildingRoomInfo(PersonInfo? info, String areaName,
-          String? buildingName, DateTime? date) =>
+          String? buildingName, DateTime? date) async =>
```
Comment (w568w) [inline lib/repository/fdu/empty_classroom_repository.dart:126]: In fact you do not need an `async` keyword here, since `UISLoginTool.tryAsyncWithAuth` returns a `Future`. Let's prevent unnecessary changes…

**Review by w568w — CHANGES_REQUESTED** [review]

**Comment by w568w** [comment]
Most look good to me and some bug-fixes are impressive. Good PR :+1:

File: lib/page/dashboard/empty_classroom_detail.dart (hunk 1 above)
Comment (kooWZ) [reply lib/page/dashboard/empty_classroom_detail.dart:124]: I can't think of a good solution.
If we use a boolean to decide whether to show the alert and call `setState` after checking connection, the widget containing classroom information will also be reloaded.
All I can think of is wrapping everything in a big `FutureWidget` , but that seems strange.

Comment (kooWZ) [reply lib/page/dashboard/empty_classroom_detail.dart:124]: ..Or use another `FutureWidget` like this:
```dart
              FutureWidget<bool>(
                future:
                    EmptyClassroomRepository.getInstance().checkConnection(),
                successBuilder: (BuildContext context,
                        AsyncSnapshot<dynamic> snapshot) =>
                    snapshot.data!
                        ? Container()
                        : Card(
                        color: Theme.of(context).colorScheme.error,
                        child: ListTile(
                          visualDensity: VisualDensity.comfortable,
                          title: Text(
                            S.of(context).limited_mode_title,
                            style: const TextStyle(color: Colors.white),
                          ),
                          subtitle: Text(
                              S.of(context).empty_classroom_warning,
                              style: const TextStyle(color: Colors.white)),
                        )),
                errorBuilder: Container(),
                loadingBuilder: Container(),
              ),
```
In this case we will have to send an extra network request

Comment (w568w) [reply lib/page/dashboard/empty_classroom_detail.dart:124]: > I can't think of a good solution.

IMMO the solution is quite simple: `getRoomInfo` knows which source it is using and `successBuilder` needs it; so make `getRoomInfo` also return the source.

You can use either [`Pair`](https://github.com/DanXi-Dev/DanXi/blob/main/lib/model/pair.dart) or [`Records`](https://dart.dev/language/records) to achieve this.

Comment (kooWZ) [reply lib/page/dashboard/empty_classroom_detail.dart:124]: But the alert should be shown on the top of the page, which is not inside the `FutureWidget`.
So I said *wrapping everything in a big `FutureWidget`*, but it seems strange

Comment (kooWZ) [reply lib/page/dashboard/empty_classroom_detail.dart]: Maybe take a look at commit [05fd513](https://github.com/DanXi-Dev/DanXi/pull/291/commits/05fd51326766fdff8261ba6613afdf4f808e4996) to see if it's an ideal approach?

Comment (w568w) [reply lib/page/dashboard/empty_classroom_detail.dart]: > Maybe take a look at commit [05fd513](https://github.com/DanXi-Dev/DanXi/pull/291/commits/05fd51326766fdff8261ba6613afdf4f808e4996) to see if it's an ideal approach?

LGTM. Will test it later.

**Review by w568w — APPROVED** [review]
Wonderful! :fireworks:

**Comment by ivanfei-1** [comment]
🧇
