### PR TITLE
fix(ui): resolve layout overflow in post headers by adopting Wrap-based spacing

### LINKED ISSUE #661: [BUG] 贴子状态栏溢出
**描述 Bug**
当状态标签较多时，贴子状态栏会溢出，将 toolbar 顶到屏幕外。

**复现步骤**
复现该 Bug 的步骤：
1. 找一个状态标签较多的贴子。
2. 进入详情页。
3. 可以看到该 bug。

**截图**
Image

**系统信息**
 - 旦挞校园助手版本（见「设置-关于本应用」）：1.5.0+347

### PR DESCRIPTION
**Pull request by sseu-buhzzi**
Fixes #661.

Addresses chips overflow in the forum post headers.

Main changes:
- Replaced `Row`s with `Wrap`s in hole and floor widget headers.
- Implemented `Expanded` with dynamic flex weights in the case where tags and chips are in one line, and both could be many in number, to ensure a balanced distribution of horizontal space.
- Removed some manual `SizedBox` insertions and utilized spacing properties.
- Unified chips generation by a shared `generateChipWidgets` function. A minor difference is that the pinned chip is always at the end now.

### CODE REVIEW

File: lib/widget/forum/forum_widgets.dart [hunk 1]
```diff
@@ -423,91 +444,34 @@ class OTFloorWidget extends StatelessWidget {
...
+                    child: Wrap(
+                      direction: Axis.horizontal,
+                      spacing: 4,
+                      runSpacing: 4,
+                      crossAxisAlignment: WrapCrossAlignment.center,
+                      children: [
+                        ColoredBox(
+                            color: nameColor,
+                            child: const SizedBox(width: 2, height: 12)),
+                        const SizedBox(),
```
Comment (w568w) [inline lib/widget/forum/forum_widgets.dart:457]: What's this `SizedBox` for?

File: lib/widget/forum/forum_widgets.dart [hunk 2]
```diff
@@ -423,91 +444,34 @@ class OTFloorWidget extends StatelessWidget {
...
-                      ],
-                      // Show pinned tag if this hole is in the pinned list and this is the first floor
-                      if (isPinned &&
-                          floor.floor_id ==
-                              parentHole?.floors?.first_floor?.floor_id) ...[
-                        const SizedBox(width: 4),
-                        LeadingChip(
-                          color: Theme.of(context).colorScheme.primary,
-                          label: S.of(context).pinned,
+                        const SizedBox(),
```
Comment (w568w) [inline lib/widget/forum/forum_widgets.dart:466]: Ditto.

**Review by w568w — CHANGES_REQUESTED** [review]

File: lib/widget/forum/forum_widgets.dart (hunk 1 above)
Comment (sseu-buhzzi) [reply lib/widget/forum/forum_widgets.dart:457]: It is to keep previous wider padding.
https://github.com/DanXi-Dev/DanXi/blob/8b5372b40328d931d6a3f4289f6d7df754fb39f9/lib/widget/forum/forum_widgets.dart#L428-L432

Previous:
`Widget | SizedBox(8) | Widget | SizedBox(4) | Widget | ...`

Now:
(spacing: 4, at each `|`)
`Widget | SizedBox(0) | Widget | Widget | ...`
